Repository jannaesteban/Blog_Site-BE, pull requests merged in 2021-11, with the labels that each got.

#45 <DB-IMP> deleted ALL_PRIVILEGES Authority and added new instead
  src/main/resources/data.sql
Labels: database

#46 Feature/create user
  src/main/java/com/example/demo/domain/appUser/NewUser.java
  src/main/java/com/example/demo/domain/appUser/UserController.java
  src/main/java/com/example/demo/domain/appUser/UserService.java
  src/main/java/com/example/demo/domain/appUser/UserServiceImpl.java
Labels: enhancement

#47 <ALL-IMP> improved endpoints, methods and security
  src/main/java/com/example/demo/domain/appUser/User.java
  src/main/java/com/example/demo/domain/appUser/UserController.java
  src/main/java/com/example/demo/domain/appUser/UserService.java
  src/main/java/com/example/demo/domain/appUser/UserServiceImpl.java
  src/main/java/com/example/demo/domain/authority/Authority.java
  src/main/java/com/example/demo/domain/exception/UserException.java
  src/main/java/com/example/demo/domain/security/SecurityConfig.java
Labels: bug, enhancement, feature

#48 <CO> added swagger feature and modified readme file
  README.md
  build.gradle
  src/main/java/com/example/demo/DemoApplication.java
Labels: documentation, enhancement, feature

#49 <DB> changed Role GUEST to SUPERVISOR, and gave authorities
  src/main/resources/data.sql
Labels: database

#50 Improvement/endpoints mapper and roles
  src/main/java/com/example/demo/domain/appUser/UserController.java
  src/main/java/com/example/demo/domain/appUser/UserService.java
  src/main/java/com/example/demo/domain/appUser/UserServiceImpl.java
Labels: improvement

#51 <ALL-IMP-CO> improved put endpoint - admin can change the role of use…
  src/main/java/com/example/demo/domain/appUser/UserController.java
  src/main/java/com/example/demo/domain/appUser/UserService.java
  src/main/java/com/example/demo/domain/appUser/UserServiceImpl.java
Labels: security, improvement
